version: '3'  # version of Docker Compose file

services:             # Services and Constainers for application
  db:                 # MySql database Container 
  # For this I uses the mysql:5.7 image, mounts a volume named db_data to persist the database data, sets environment variables for the MySQL configuration, and connects it to the wpsite network.
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite

  phpmyadmin:        # Service PhpMyAdmin for web based interface so we can manage MySql database
  # uses the phpmyadmin/phpmyadmin image, maps port 8080 on the host to port 80 in the container, sets environment variables for the phpMyAdmin configuration, and connects it to the wpsite network.
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - wpsite

  wordpress:        # Service WordPress container.
  # depends on the db service, uses the wordpress:latest image, maps port 8000 on the host to port 80 in the container, mounts the current directory (./) to the /var/www/html directory in the container, sets environment variables for the WordPress configuration, and connects it to the wpsite network.
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    volumes:
      - './:/var/www/html'
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpsite

networks:     # Define the network
  wpsite:

volumes:     # define Volume used by the service
  db_data: